; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Placeholder Tune
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env19,@env13,@env12,@env0 ; 00 : Snare
	.word @env16,@env15,@env12,@env0 ; 01 : NoiseHiHat2
	.word @env17,@env15,@env12,@env0 ; 02 : NoiseHitHat1
	.word @env4,@env8,@env2,@env0 ; 03 : Lead
	.word @env10,@env7,@env12,@env3 ; 04 : SqGuitarOctave
	.word @env9,@env8,@env14,@env0 ; 05 : Lead (Short)
	.word @env10,@env6,@env1,@env18 ; 06 : SqGuitarOctaveAlt
	.word @env5,@env8,@env12,@env0 ; 07 : Bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $c2,$c1,$00,$01
@env3:
	.byte $00,$c0,$c0,$c1,$00,$03
@env4:
	.byte $09,$c4,$c5,$c4,$c4,$c3,$c2,$00,$04,$c1,$c1,$c0,$00,$0b
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$d3,$c0,$00,$02
@env7:
	.byte $c0,$cc,$c0,$00,$02
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $00,$c4,$c5,$c4,$c3,$c2,$00,$05
@env10:
	.byte $00,$c4,$7f,$00,$02
@env11:
	.byte $00,$c0,$be,$bd,$bc,$02,$bd,$be,$c0,$c2,$c3,$c4,$02,$c3,$c2,$00,$01
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $c0,$c8,$ca,$cb,$ca,$cb,$cc,$ce,$00,$07
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $c0,$c2,$00,$01
@env16:
	.byte $00,$c3,$c3,$c2,$c1,$c0,$00,$05
@env17:
	.byte $00,$c4,$02,$c3,$02,$c2,$02,$c1,$00,$07
@env18:
	.byte $00,$c0,$c1,$00,$02
@env19:
	.byte $00,$ce,$c8,$c3,$c4,$c3,$c1,$00,$06
@env20:
	.byte $00,$c0,$b7,$b5,$bb,$c5,$cb,$c9,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0b,$0f,$40 ; 00 Sample 1 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $ff, $ed, $48, $ff, $ef, $48, $7b, $86
@song0ref14:
	.byte $2e, $8d, $45, $8b, $2a, $8d, $45, $8b, $2c, $8d, $45, $8b, $2e, $8d, $45, $8b, $33, $8d, $45, $8b, $31, $8d, $45, $8b
	.byte $2f, $8d, $45, $8b, $31, $8d, $45, $8b, $48
	.byte $41, $20
	.word @song0ref14
	.byte $48, $7f, $88, $50, $e8, $33, $3d, $8d, $31, $b9, $50, $fc, $3d, $3f, $8b, $33, $b1, $2e, $85, $30, $8d, $2c, $8b, $27
	.byte $9b, $50, $f7, $33, $3a, $9b, $48, $2e, $8d, $2c, $9b, $30, $8b, $2f, $87, $2e, $83, $2c, $8b, $31, $93, $30, $95, $2e
	.byte $8b, $2f, $8d, $30, $8b, $33, $9b, $50, $fc, $3f, $44, $9b, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $00, $ff, $ed, $ff, $ef, $8a
@song0ref120:
	.byte $1e, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $85, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $83, $49, .lobyte(@env20), .hibyte(@env20), $99
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $22, $8d, $25, $8b, $2a, $8d, $25, $8b, $19, $8d, $49, .lobyte(@env11)
	.byte .hibyte(@env11), $8b, $49, .lobyte(@env20), .hibyte(@env20), $9f, $8a, $1d, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $8d, $20, $8b, $23, $9b
	.byte $41, $18
	.word @song0ref120
	.byte $7c, $8c
@song0ref184:
	.byte $1e, $8d, $1e, $83, $25, $85, $1e, $87, $25, $83, $1e, $83, $25, $85, $20, $87, $27, $83, $20, $83, $27, $85, $20, $87
	.byte $27, $83, $20, $83, $27, $85, $1d, $87, $1d, $83, $20, $83, $20, $85, $24, $87, $24, $83, $20, $83, $20, $85, $1b, $87
	.byte $22, $83, $1b, $83, $22, $85, $1b, $87, $22, $83, $1b, $83, $22, $85
	.byte $41, $3e
	.word @song0ref184
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8e
@song0ref254:
	.byte $12, $b9, $00, $9b, $14, $9b, $19, $9b, $14, $9b, $0d, $b9
	.byte $41, $0c
	.word @song0ref254
	.byte $41, $0c
	.word @song0ref254
	.byte $41, $0c
	.word @song0ref254
@song0ref275:
	.byte $12, $8d, $00, $8b, $12, $8d, $19, $8b, $14, $8d, $00, $8b, $14, $8d, $16, $8b, $11, $8d, $14, $8b, $11, $9b, $0f, $b9
	.byte $41, $18
	.word @song0ref275
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $82
@song0ref307:
	.byte $2e, $8d, $00, $8b, $2c, $8d, $00, $8b, $80, $25, $9b, $82, $2c, $8d, $00, $8b
	.byte $41, $0e
	.word @song0ref307
	.byte $41, $0c
	.word @song0ref307
@song0ref329:
	.byte $80, $25, $8b, $82, $2e, $8d, $80, $25, $8b, $00, $9b, $25, $9b, $82, $2c, $8d, $00, $8b
	.byte $41, $0e
	.word @song0ref307
	.byte $41, $0e
	.word @song0ref307
	.byte $41, $0c
	.word @song0ref307
	.byte $41, $0e
	.word @song0ref329
	.byte $84
	.byte $41, $0a
	.word @song0ref307
	.byte $84, $2c, $8d, $00, $8b
	.byte $41, $0a
	.word @song0ref307
	.byte $84, $2c, $8d, $00, $8b, $bb, $80, $25, $9b, $00, $9b, $25, $8d, $00, $a9, $25, $8d, $25, $8b, $00, $9b, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref396:
	.byte $01, $9b, $00, $f5, $01, $8d, $01, $8b, $00, $b9, $01, $8d, $00, $8b, $01, $8d, $00, $a9, $01, $8d, $00, $a9, $01, $8d
	.byte $01, $8b, $00, $ab, $01, $8b
	.byte $41, $1e
	.word @song0ref396
	.byte $41, $1e
	.word @song0ref396
	.byte $42
	.word @song0ch4loop
